package entity;

public enum Language {
    ABKHAZ("Abkhaz"),
    ACEHNESE("Acehnese"),
    ACHOLI("Acholi"),
    AFRIKAANS("Afrikaans", "af"),
    ALBANIAN("Albanian"),
    ALUR("Alur"),
    AMHARIC("Amharic"),
    ARABIC("Arabic", "ar"),
    ARMENIAN("Armenian", "hy"),
    ASSAMESE("Assamese", "as"),
    AWADHI("Awadhi"),
    AYMARA("Aymara", "ay"),
    AZERBAIJANI("Azerbaijani", "az"),
    BALINESE("Balinese"),
    BAMBARA("Bambara"),
    BASHKIR("Bashkir", "ba"),
    BASQUE("Basque", "eu"),
    BATAK("Batak"),
    BATAK_SIMALUNGUN("Batak Simalungun"),
    BATAK_TOBA("Batak Toba"),
    BELARUSIAN("Belarusian", "be"),
    BEMBA("Bemba", ""),
    BENGALI("Bengali"),
    BETAWI("Betawi"),
    BHOJPURI("Bhojpuri"),
    BIKOL("Bikol"),
    BOSNIAN("Bosnian"),
    BRETON("Breton"),
    BULGARIAN("Bulgarian"),
    BURYAT("Buryat"),
    CANTONESE("Cantonese"),
    CATALAN("Catalan"),
    CEBUANO("Cebuano"),
    CHICHEWA("Chichewa (Nyanja)"),
    CHINESE_SIMPLIFIED("Chinese (Simplified)", "zh"),
    CHINESE_TRADITIONAL("Chinese (Traditional)", "zh-TW"),
    CHUVASH("Chuvash"),
    CORSICAN("Corsican", "co"),
    CRIMEAN_TATAR("Crimean Tatar"),
    CROATIAN("Croatian", "hr"),
    CZECH("Czech", "cz"),
    DANISH("Danish", "da"),
    DINKA("Dinka"),
    DIVEHI("Divehi", "dv"),
    DOGRI("Dogri"),
    DOMBE("Dombe"),
    DUTCH("Dutch", "nl"),
    DZONGKHA("Dzongkha"),
    ENGLISH("English", "en"),
    ESPERANTO("Esperanto", "eo"),
    ESTONIAN("Estonian", "et"),
    EWE("Ewe", "ee"),
    FIJIAN("Fijian"),
    FILIPINO_TAGALOG("Filipino (Tagalog)"),
    FINNISH("Finnish", "fi"),
    FRENCH("French", "fr"),
    FRISIAN("Frisian", "fy"),
    FULFULDE("Fulfulde"),
    GA("Ga"),
    GALICIAN("Galician", "gl"),
    GANDA("Ganda (Luganda)"),
    GEORGIAN("Georgian", "ka"),
    GERMAN("German", "de"),
    GREEK("Greek","el"),
    GUARANI("Guarani", "gn"),
    GUJARATI("Gujarati", "gu"),
    HAITIAN_CREOLE("Haitian Creole", "ht"),
    HAKHA_CHIN("Hakha Chin"),
    HAUSA("Hausa", "ha"),
    HAWAIIAN("Hawaiian", "haw"),
    HEBREW("Hebrew", "he"),
    HILIGAYNON("Hiligaynon"),
    HINDI("Hindi", "hi"),
    HMONG("Hmong", "hmn"),
    HUNGARIAN("Hungarian", "hu"),
    HUNSRIK("Hunsrik"),
    ICELANDIC("Icelandic", "is"),
    IGBO("Igbo", "ig"),
    ILOCANO("Ilocano", "ilo"),
    INDONESIAN("Indonesian", "id"),
    IRISH("Irish", "ga"),
    ITALIAN("Italian", "it"),
    JAPANESE("Japanese", "ja"),
    JAVANESE("Javanese", "jv"),
    KANNADA("Kannada", "kn"),
    KAPAMPANGAN("Kapampangan"),
    KAZAKH("Kazakh", "kk"),
    KHMER("Khmer", "km"),
    KIGA("Kiga"),
    KINYARWANDA("Kinyarwanda", "rw"),
    KITUBA("Kituba"),
    KONKANI("Konkani", "gom"),
    KOREAN("Korean", "ko"),
    KRIO("Krio", "kri"),
    KURDISH_KURMANJI("Kurdish (Kurmanji)", "ku"),
    KURDISH_SORANI("Kurdish (Sorani)", "ckb"),
    KYRGYZ("Kyrgyz", "ky"),
    LAO("Lao", "lo"),
    LATGALIAN("Latgalian"),
    LATIN("Latin", "la"),
    LATVIAN("Latvian", "lv"),
    LIGURIAN("Ligurian"),
    LIMBURGAN("Limburgan"),
    LINGALA("Lingala", "ln"),
    LITHUANIAN("Lithuanian", "lt"),
    LOMBARD("Lombard"),
    LUGANDA("Luganda", "lg"),
    LUO("Luo"),
    LUXEMBOURGISH("Luxembourgish", "lb"),
    MACEDONIAN("Macedonian", "mk"),
    MAITHILI("Maithili", "mai"),
    MAKASSAR("Makassar"),
    MALAGASY("Malagasy", "mg"),
    MALAY("Malay", "ms"),
    MALAY_JAWI("Malay (Jawi)"),
    MALAYALAM("Malayalam", "ml"),
    MALTESE("Maltese", "mt"),
    MAORI("Maori", "mi"),
    MARATHI("Marathi", "mr"),
    MEADOW_MARI("Meadow Mari"),
    MEITEILON("Meiteilon (Manipuri)", "mni-Mtei"),
    MINANG("Minang"),
    MIZO("Mizo", "lus"),
    MONGOLIAN("Mongolian", "mn"),
    MYANMAR_BURMESE("Myanmar (Burmese)", "my"),
    NDEBELE_SOUTH("Ndebele (South)"),
    NEPALBHASA("Nepalbhasa (Newari)"),
    NEPALI("Nepali", "ne"),
    NORTHERN_SOTHO("Northern Sotho (Sepedi)"),
    NORWEGIAN("Norwegian", "no"),
    NUER("Nuer"),
    OCCITAN("Occitan"),
    ODIA("Odia (Oriya)", "or"),
    OROMO("Oromo", "om"),
    PANGASINAN("Pangasinan"),
    PAPIAMENTO("Papiamento"),
    PASHTO("Pashto", "ps"),
    PERSIAN("Persian", "fa"),
    POLISH("Polish", "pl"),
    PORTUGUESE("Portuguese", "pt"),
    PORTUGUESE_PORTUGAL("Portuguese (Portugal)"),
    PORTUGUESE_BRAZIL("Portuguese (Brazil)"),
    PUNJABI("Punjabi", "pa"),
    PUNJABI_SHAHMUKHI("Punjabi (Shahmukhi)"),
    QUECHUA("Quechua", "qu"),
    ROMANI("Romani"),
    ROMANIAN("Romanian", "ro"),
    RUNDI("Rundi"),
    RUSSIAN("Russian", "ru"),
    SAMOAN("Samoan", "sm"),
    SANGO("Sango"),
    SANSKRIT("Sanskrit", "sa"),
    SCOTS_GAELIC("Scots Gaelic", "gd"),
    SERBIAN("Serbian", "sr"),
    SESOTHO("Sesotho", "st"),
    SEYCHELLOIS_CREOLE("Seychellois Creole"),
    SHAN("Shan"),
    SHONA("Shona", "sn"),
    SICILIAN("Sicilian"),
    SILESIAN("Silesian"),
    SINDHI("Sindhi", "sd"),
    SINHALA("Sinhala (Sinhalese)", "si"),
    SLOVAK("Slovak", "sk"),
    SLOVENIAN("Slovenian", "sl"),
    SOMALI("Somali", "so"),
    SPANISH("Spanish", "es"),
    SUNDANESE("Sundanese", "su"),
    SWAHILI("Swahili", "sw"),
    SWATI("Swati"),
    SWEDISH("Swedish", "sv"),
    TAGALOG("Tagalog", "tl"),
    TAJIK("Tajik", "tg"),
    TAMIL("Tamil", "ta"),
    TATAR("Tatar", "tt"),
    TELUGU("Telugu", "te"),
    TETUM("Tetum"),
    THAI("Thai", "th"),
    TIGRINYA("Tigrinya", "ti"),
    TSONGA("Tsonga", "ts"),
    TSWANA("Tswana"),
    TURKISH("Turkish", "tr"),
    TURKMEN("Turkmen", "tk"),
    TWI_AKAN("Twi (Akan)", "tw"),
    UKRAINIAN("Ukrainian", "uk"),
    URDU("Urdu", "ur"),
    UYGHUR("Uyghur", "ug"),
    UZBEK("Uzbek", "uz"),
    VIETNAMESE("Vietnamese", "vi"),
    WELSH("Welsh", "cy"),
    WOLOF("Wolof", "wo"),
    XHOSA("Xhosa", "xh"),
    YIDDISH("Yiddish", "yi"),
    YORUBA("Yoruba", "yo"),
    YUCATEC_MAYA("Yucatec Maya"),
    ZULU("Zulu", "zu");

    private final String displayName;
    private final String isoCode;

    Language(String displayName, String isoCode) {
        this.displayName = displayName;
        this.isoCode = isoCode;
    }

    public String getDisplayName() {
        return displayName;
    }

    public String getIsoCode() {return isoCode;}

    @Override
    public String toString() {
        return displayName;
    }
}