package entity;

public enum Language {
    ABKHAZ("Abkhaz", "ab"),
    ACEHNESE("Acehnese", "ach"),
    AFAR("Afar", "aa"),
    AFRIKAANS("Afrikaans", "af"),
    ALBANIAN("Albanian", "sq"),
    ALUR("Alur", "alz"),
    AMHARIC("Amharic", "am"),
    ARABIC("Arabic", "ar"),
    ARMENIAN("Armenian", "hy"),
    ASSAMESE("Assamese", "as"),
    AVAR("Avar", "av"),
    AWADHIN("Awadhi", "awa"),
    AYMARA("Aymara", "ay"),
    AZERBAIJANI("Azerbaijani", "az"),
    BALINESE("Balinese", "ban"),
    BASHKIR("Bashkir", "ba"),
    BASQUE("Basque", "eu"),
    BATAK_TOBA("Batak Toba", "bbc"),
    BELARUSIAN("Belarusian", "be"),
    BEMBA("Bemba", "bem"),
    BENGALI("Bengali", "bn"),
    BETAWI("Betawi", "bew"),
    BHOJPURI("Bhojpuri", "bho"),
    BIKOL("Bikol", "bik"),
    BOSNIAN("Bosnian", "bs"),
    BODO("Bodo", null),
    BRETON("Breton", "br"),
    BULGARIAN("Bulgarian", "bg"),
    BURYAT("Buryat", "bua"),
    CANTONESE("Cantonese", "yue"),
    CATALAN("Catalan", "ca"),
    CEBUANO("Cebuano", "ceb"),
    CHEROKEE("Cherokee", null),
    CHICHEWA("Chichewa (Nyanja)", "ny"),
    CHINESE_SIMPLIFIED("Chinese (Simplified)", "zh"),
    CHINESE_TRADITIONAL("Chinese (Traditional)", "zh-TW"),
    CHUVASH("Chuvash", "cv"),
    CORSICAN("Corsican", "co"),
    CRIMEAN_TATAR("Crimean Tatar", "crh"),
    CROATIAN("Croatian", "hr"),
    CZECH("Czech", "cs"),
    DANISH("Danish", "da"),
    DINKA("Dinka", "din"),
    DIVEHI("Divehi", "dv"),
    DOGRI("Dogri", "doi"),
    DOMBE("Dombe", null),
    DUTCH("Dutch", "nl"),
    DZONGKHA("Dzongkha", "dz"),
    ENGLISH("English", "en"),
    ESPERANTO("Esperanto", "eo"),
    ESTONIAN("Estonian", "et"),
    EWE("Ewe", "ee"),
    FIJIAN("Fijian", "fj"),
    FINNISH("Finnish", "fi"),
    FRENCH("French", "fr"),
    FRISIAN("Frisian", "fy"),
    FULFULDE("Fulfulde", "ff"),
    GA("Ga", "gaa"),
    GALICIAN("Galician", "gl"),
    GANDA("Ganda (Luganda)", "lg"),
    GEORGIAN("Georgian", "ka"),
    GERMAN("German", "de"),
    GREEK("Greek", "el"),
    GUARANI("Guarani", "gn"),
    GUJARATI("Gujarati", "gu"),
    HAITIAN_CREOLE("Haitian Creole", "ht"),
    HAKHA_CHIN("Hakha Chin", "cnh"),
    HAUSA("Hausa", "ha"),
    HAWAIIAN("Hawaiian", "haw"),
    HEBREW("Hebrew", "he"),
    HILIGAYNON("Hiligaynon", "hil"),
    HINDI("Hindi", "hi"),
    HMONG("Hmong", "hmn"),
    HUNGARIAN("Hungarian", "hu"),
    HUNSRIK("Hunsrik", "hrx"),
    ICELANDIC("Icelandic", "is"),
    IGBO("Igbo", "ig"),
    ILOCANO("Ilocano", "ilo"),
    INDONESIAN("Indonesian", "id"),
    IRISH("Irish", "ga"),
    ITALIAN("Italian", "it"),
    JAPANESE("Japanese", "ja"),
    JAVANESE("Javanese", "jv"),
    KANNADA("Kannada", "kn"),
    KAPAMPANGAN("Kapampangan", "pam"),
    KAZAKH("Kazakh", "kk"),
    KHMER("Khmer", "km"),
    KIGA("Kiga", "cgg"),
    KINYARWANDA("Kinyarwanda", "rw"),
    KITUBA("Kituba", "ktu"),
    KONKANI("Konkani", "gom"),
    KOREAN("Korean", "ko"),
    KRIO("Krio", "kri"),
    KURDISH_KURMANJI("Kurdish (Kurmanji)", "ku"),
    KURDISH_SORANI("Kurdish (Sorani)", "ckb"),
    KYRGYZ("Kyrgyz", "ky"),
    LAO("Lao", "lo"),
    LATGALIAN("Latgalian", "ltg"),
    LATIN("Latin", "la"),
    LATVIAN("Latvian", "lv"),
    LIGURIAN("Ligurian", "lij"),
    LIMBURGAN("Limburgan", "li"),
    LINGALA("Lingala", "ln"),
    LITHUANIAN("Lithuanian", "lt"),
    LOMBARD("Lombard", "lmo"),
    LOZI("Lozi", null),
    LUGANDA("Luganda", "lg"),
    LUO("Luo", "luo"),
    LUXEMBOURGISH("Luxembourgish", "lb"),
    MACEDONIAN("Macedonian", "mk"),
    MAITHILI("Maithili", "mai"),
    MAKASSAR("Makassar", "mak"),
    MALAGASY("Malagasy", "mg"),
    MALAY("Malay", "ms"),
    MALAY_JAWI("Malay (Jawi)", "ms-arab"),
    MALAYALAM("Malayalam", "ml"),
    MALTESE("Maltese", "mt"),
    MANX("Manx", "gv"),
    MAORI("Maori", "mi"),
    MARATHI("Marathi", "mr"),
    MEADOW_MARI("Meadow Mari", "mhr"),
    MEITEILON("Meiteilon (Manipuri)", "mni-Mtei"),
    MINANG("Minang", "min"),
    MIZO("Mizo", "lus"),
    MONGOLIAN("Mongolian", "mn"),
    MYANMAR_BURMESE("Myanmar (Burmese)", "my"),
    NAHUATL("Nahuatl", "nhe"),
    NDEBELE_SOUTH("Ndebele (South)", "nr"),
    NEPALBHASA("Nepalbhasa (Newari)", "new"),
    NEPALI("Nepali", "ne"),
    NKO("NKo", null),
    NORTHERN_SOTHO("Northern Sotho (Sepedi)", "nso"),
    NORWEGIAN("Norwegian", "no"),
    NUER("Nuer", "nus"),
    OCCITAN("Occitan", "oc"),
    ODIA("Odia (Oriya)", "or"),
    OROMO("Oromo", "om"),
    PANGASINAN("Pangasinan", "pag"),
    PAPIAMENTO("Papiamento", "pap"),
    PASHTO("Pashto", "ps"),
    PERSIAN("Persian", "fa"),
    POLISH("Polish", "pl"),
    PORTUGUESE("Portuguese", "pt"),
    PORTUGUESE_PORTUGAL("Portuguese (Portugal)", "pt-PT"),
    PORTUGUESE_BRAZIL("Portuguese (Brazil)", "pt-BR"),
    PUNJABI("Punjabi", "pa"),
    QUECHUA("Quechua", "qu"),
    ROMANI("Romani", "rom"),
    ROMANIAN("Romanian", "ro"),
    RUNDI("Rundi", "rn"),
    RUSSIAN("Russian", "ru"),
    SAMOAN("Samoan", "sm"),
    SANGO("Sango", "sg"),
    SANSKRIT("Sanskrit", "sa"),
    SCOTS_GAELIC("Scots Gaelic", "gd"),
    SERBIAN("Serbian", "sr"),
    SESOTHO("Sesotho", "st"),
    SEYCHELLOIS_CREOLE("Seychellois Creole", "crs"),
    SHAN("Shan", "shn"),
    SHONA("Shona", "sn"),
    SICILIAN("Sicilian", "scn"),
    SILESIAN("Silesian", "szl"),
    SINDHI("Sindhi", "sd"),
    SINHALA("Sinhala (Sinhalese)", "si"),
    SLOVAK("Slovak", "sk"),
    SLOVENIAN("Slovenian", "sl"),
    SOMALI("Somali", "so"),
    SPANISH("Spanish", "es"),
    SUNDANESE("Sundanese", "su"),
    SWAHILI("Swahili", "sw"),
    SWATI("Swati", "ss"),
    SWEDISH("Swedish", "sv"),
    TAGALOG("Tagalog", "tl"),
    TAHITIAN("Tahitian", "ty"),
    TAJIK("Tajik", "tg"),
    TAMIL("Tamil", "ta"),
    TATAR("Tatar", "tt"),
    TELUGU("Telugu", "te"),
    TETUM("Tetum", "tet"),
    THAI("Thai", "th"),
    TIGRINYA("Tigrinya", "ti"),
    TSONGA("Tsonga", "ts"),
    TSWANA("Tswana", "tn"),
    TURKISH("Turkish", "tr"),
    TURKMEN("Turkmen", "tk"),
    TWI_AKAN("Twi (Akan)", "tw"),
    UKRAINIAN("Ukrainian", "uk"),
    URDU("Urdu", "ur"),
    UYGHUR("Uyghur", "ug"),
    UZBEK("Uzbek", "uz"),
    VENDA("Venda", "ve"),
    VIETNAMESE("Vietnamese", "vi"),
    WELSH("Welsh", "cy"),
    WOLOF("Wolof", "wo"),
    XHOSA("Xhosa", "xh"),
    YIDDISH("Yiddish", "yi"),
    YORUBA("Yoruba", "yo"),
    YUCATEC_MAYA("Yucatec Maya", "yua"),
    ZULU("Zulu", "zu");

    private final String displayName;
    private final String isoCode;

    Language(String displayName, String isoCode) {
        this.displayName = displayName;
        this.isoCode = isoCode;
    }

    public String getDisplayName() {
        return displayName;
    }

    public String getIsoCode() {
        return isoCode;
    }

    @Override
    public String toString() {
        return displayName;
    }
}
