package entity;

public enum Language {
    ACEHNESE("Acehnese", "ach"),
    AFRIKAANS("Afrikaans", "af"),
    ALBANIAN("Albanian", "sq"),
    AMHARIC("Amharic", "am"),
    ARABIC("Arabic", "ar"),
    ARMENIAN("Armenian", "hy"),
    ASSAMESE("Assamese", "as"),
    AYMARA("Aymara", "ay"),
    AZERBAIJANI("Azerbaijani", "az"),
    BALINESE("Balinese", null),
    BASHKIR("Bashkir", "ba"),
    BASQUE("Basque", "eu"),
    BATAK_TOBA("Batak Toba", null),
    BELARUSIAN("Belarusian", "be"),
    BEMBA("Bemba", "bem"),
    BENGALI("Bengali", "bn"),
    BETAWI("Betawi", null),
    BHOJPURI("Bhojpuri", "bho"),
    BIKOL("Bikol", null),
    BOSNIAN("Bosnian", "bs"),
    BODO("Bodo", "brx"),
    BULGARIAN("Bulgarian", "bg"),
    BURYAT("Buryat", null),
    CANTONESE("Cantonese", null),
    CATALAN("Catalan", "ca"),
    CEBUANO("Cebuano", "ceb"),
    CHICHEWA("Chichewa (Nyanja)", "ny"),
    CHINESE_SIMPLIFIED("Chinese (Simplified)", "zh"),
    CHINESE_TRADITIONAL("Chinese (Traditional)", "zh-TW"),
    CHUVASH("Chuvash", null),
    CORSICAN("Corsican", "co"),
    CRIMEAN_TATAR("Crimean Tatar", null),
    CROATIAN("Croatian", "hr"),
    CZECH("Czech", "cs"),
    DANISH("Danish", "da"),
    DINKA("Dinka", null),
    DIVEHI("Divehi", "dv"),
    DOGRI("Dogri", null),
    DOMBE("Dombe", null),
    DUTCH("Dutch", "nl"),
    DZONGKHA("Dzongkha", null),
    ENGLISH("English", "en"),
    ESPERANTO("Esperanto", "eo"),
    ESTONIAN("Estonian", "et"),
    EWE("Ewe", "ee"),
    FIJIAN("Fijian", null),
    FINNISH("Finnish", "fi"),
    FRENCH("French", "fr"),
    FRISIAN("Frisian", "fy"),
    FULFULDE("Fulfulde", null),
    GA("Ga", null),
    GALICIAN("Galician", "gl"),
    GANDA("Ganda (Luganda)", null),
    GEORGIAN("Georgian", "ka"),
    GERMAN("German", "de"),
    GREEK("Greek","el"),
    GUARANI("Guarani", "gn"),
    GUJARATI("Gujarati", "gu"),
    HAITIAN_CREOLE("Haitian Creole", "ht"),
    HAKHA_CHIN("Hakha Chin", null),
    HAUSA("Hausa", "ha"),
    HAWAIIAN("Hawaiian", "haw"),
    HEBREW("Hebrew", "he"),
    HILIGAYNON("Hiligaynon", null),
    HINDI("Hindi", "hi"),
    HMONG("Hmong", "hmn"),
    HUNGARIAN("Hungarian", "hu"),
    HUNSRIK("Hunsrik", null),
    ICELANDIC("Icelandic", "is"),
    IGBO("Igbo", "ig"),
    ILOCANO("Ilocano", "ilo"),
    INDONESIAN("Indonesian", "id"),
    IRISH("Irish", "ga"),
    ITALIAN("Italian", "it"),
    JAPANESE("Japanese", "ja"),
    JAVANESE("Javanese", "jv"),
    KANNADA("Kannada", "kn"),
    KAPAMPANGAN("Kapampangan", null),
    KAZAKH("Kazakh", "kk"),
    KHMER("Khmer", "km"),
    KIGA("Kiga", null),
    KINYARWANDA("Kinyarwanda", "rw"),
    KITUBA("Kituba", null),
    KONKANI("Konkani", "gom"),
    KOREAN("Korean", "ko"),
    KRIO("Krio", "kri"),
    KURDISH_KURMANJI("Kurdish (Kurmanji)", "ku"),
    KURDISH_SORANI("Kurdish (Sorani)", "ckb"),
    KYRGYZ("Kyrgyz", "ky"),
    LAO("Lao", "lo"),
    LATGALIAN("Latgalian", null),
    LATIN("Latin", "la"),
    LATVIAN("Latvian", "lv"),
    LIGURIAN("Ligurian", null),
    LIMBURGAN("Limburgan", null),
    LINGALA("Lingala", "ln"),
    LITHUANIAN("Lithuanian", "lt"),
    LOMBARD("Lombard", null),
    LUGANDA("Luganda", "lg"),
    LUO("Luo", null),
    LUXEMBOURGISH("Luxembourgish", "lb"),
    MACEDONIAN("Macedonian", "mk"),
    MAITHILI("Maithili", "mai"),
    MAKASSAR("Makassar",null),
    MALAGASY("Malagasy", "mg"),
    MALAY("Malay", "ms"),
    MALAY_JAWI("Malay (Jawi)", null),
    MALAYALAM("Malayalam", "ml"),
    MALTESE("Maltese", "mt"),
    MAORI("Maori", "mi"),
    MARATHI("Marathi", "mr"),
    MEADOW_MARI("Meadow Mari", null),
    MEITEILON("Meiteilon (Manipuri)", "mni-Mtei"),
    MINANG("Minang",null),
    MIZO("Mizo", "lus"),
    MONGOLIAN("Mongolian", "mn"),
    MYANMAR_BURMESE("Myanmar (Burmese)", "my"),
    NDEBELE_SOUTH("Ndebele (South)", null),
    NEPALBHASA("Nepalbhasa (Newari)", null),
    NEPALI("Nepali", "ne"),
    NORTHERN_SOTHO("Northern Sotho (Sepedi)", null),
    NORWEGIAN("Norwegian", "no"),
    NUER("Nuer",null),
    OCCITAN("Occitan",null),
    ODIA("Odia (Oriya)", "or"),
    OROMO("Oromo", "om"),
    PANGASINAN("Pangasinan",null),
    PAPIAMENTO("Papiamento",null),
    PASHTO("Pashto", "ps"),
    PERSIAN("Persian", "fa"),
    POLISH("Polish", "pl"),
    PORTUGUESE("Portuguese", "pt"),
    PORTUGUESE_PORTUGAL("Portuguese (Portugal)", "pt-PT"),
    PORTUGUESE_BRAZIL("Portuguese (Brazil)", "pt-BR"),
    PUNJABI("Punjabi", "pa"),
    QUECHUA("Quechua", "qu"),
    ROMANI("Romani",null),
    ROMANIAN("Romanian", "ro"),
    RUNDI("Rundi",null),
    RUSSIAN("Russian", "ru"),
    SAMOAN("Samoan", "sm"),
    SANGO("Sango",null),
    SANSKRIT("Sanskrit", "sa"),
    SCOTS_GAELIC("Scots Gaelic", "gd"),
    SERBIAN("Serbian", "sr"),
    SESOTHO("Sesotho", "st"),
    SEYCHELLOIS_CREOLE("Seychellois Creole",null),
    SHAN("Shan",null),
    SHONA("Shona", "sn"),
    SICILIAN("Sicilian",null),
    SILESIAN("Silesian",null),
    SINDHI("Sindhi", "sd"),
    SINHALA("Sinhala (Sinhalese)", "si"),
    SLOVAK("Slovak", "sk"),
    SLOVENIAN("Slovenian", "sl"),
    SOMALI("Somali", "so"),
    SPANISH("Spanish", "es"),
    SUNDANESE("Sundanese", "su"),
    SWAHILI("Swahili", "sw"),
    SWATI("Swati",null),
    SWEDISH("Swedish", "sv"),
    TAGALOG("Tagalog", "tl"),
    TAJIK("Tajik", "tg"),
    TAMIL("Tamil", "ta"),
    TATAR("Tatar", "tt"),
    TELUGU("Telugu", "te"),
    TETUM("Tetum",null),
    THAI("Thai", "th"),
    TIGRINYA("Tigrinya", "ti"),
    TSONGA("Tsonga", "ts"),
    TSWANA("Tswana",null),
    TURKISH("Turkish", "tr"),
    TURKMEN("Turkmen", "tk"),
    TWI_AKAN("Twi (Akan)", "tw"),
    UKRAINIAN("Ukrainian", "uk"),
    URDU("Urdu", "ur"),
    UYGHUR("Uyghur", "ug"),
    UZBEK("Uzbek", "uz"),
    VIETNAMESE("Vietnamese", "vi"),
    WELSH("Welsh", "cy"),
    WOLOF("Wolof", "wo"),
    XHOSA("Xhosa", "xh"),
    YIDDISH("Yiddish", "yi"),
    YORUBA("Yoruba", "yo"),
    YUCATEC_MAYA("Yucatec Maya",null),
    ZULU("Zulu", "zu");

    private final String displayName;
    private final String isoCode;

    Language(String displayName, String isoCode) {
        this.displayName = displayName;
        this.isoCode = isoCode;
    }

    public String getDisplayName() {
        return displayName;
    }

    public String getIsoCode() {return isoCode;}

    @Override
    public String toString() {
        return displayName;
    }
}